### Global gh-pages pre-amble
safe: false
lsi: false

### The following properties will change on a project-by-project basis

# Context path in the remote website (usually /<project>), will be prepended to absolute URLs for static resources
# baseurl: /COPASI

# Name of the project for display in places like page titles
name: COPASI

# ID of the project in the metadata API at spring.io (if this is not a
# valid project ID the javascript widgets in the home page will not work)
project: COPASI

# Project github URL
github_repo_url: https://github.com/copasi/COPASI

# Exclude tmp directory
exclude: [tmp, README.md]

# Add Processing features
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Create directories for each post similar to other pages
permalink: News/:year/:month/:day/:title/

# Paginate posts
paginate: 5
paginate_path: "/News/Page_:num/"
